apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ueprofiles-5gcore
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-ue
        image: ueprofiles-5gcore-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: ueprofiles-configmap
              key: REACT_APP_API_URL
---
# frontend service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ueprofiles-5gcore
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort