apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: ueprofiles-5gcore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# mongodb deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: ueprofiles-5gcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongo-init
              mountPath: /docker-entrypoint-initdb.d/
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: ueprofiles-configmap
                  key: MONGO_DATABASE
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ueprofiles-secrets
                  key: MONGO_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ueprofiles-secrets
                  key: MONGO_PASSWORD
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
        - name: mongo-init
          configMap:
            name: mongo-init-script 
---
# mongodb service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: ueprofiles-5gcore
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
---
# mongodb configmap initialization
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
  namespace: ueprofiles-5gcore
data:
  mongo-init.js: |
    db = db.getSiblingDB('webue_db');
    db.createUser({
      user: 'user',
      pwd: 'password',
      roles: [
        {
          role: 'readWrite',
          db: 'webue_db'
        }
      ]
    });