apiVersion: v1
kind: ConfigMap
metadata:
  name: ueprofiles-configmap
  namespace: ueprofiles-5gcore
data:
  MONGO_HOST: "mongodb"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "webue_db"
  SERVER_PORT: "8080"
  REACT_APP_API_URL: "http://localhost:8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: ueprofiles-secrets
  namespace: ueprofiles-5gcore
type: Opaque
data:
  MONGO_USER: dXNlcg==  # base64 encoded 'user'
  MONGO_PASSWORD: cGFzc3dvcmQ=  # base64 encoded 'password'
  JWT_SECRET: eW91ci1zZWNyZXQta2V5  # base64 encoded 'your-secret-key'